### PR TITLE
Switch occurrences of vfs_read and vfs_write to kernel_read and kerne…

### PR DESCRIPTION
**Pull request by kaduke**
…l_write.

I was unable to compile on 4.14 without this fix.

### CODE REVIEW

**Comment by genodeftest** [comment]
Thank you!

Looks fine to me, and builds without warnings at least.

**Comment by genodeftest** [comment]
@kaduke: Would you be interested in maintaining this driver? Do you have more experience in kernel development? I'm asking because the current situation of this driver is quite bad. The code seems to break sometimes and it is not correctly maintained any more. 

If you answer yes, we might ask jurobystricky to move his code to a Github organization or open one ourselves.

**Comment by kaduke** [comment]
@genodeftest I'm pretty inexperienced with kernel development to be honest and just started dabbling recently, mainly because I needed to get this driver working for my desktop. I am interested in helping keep this driver maintained as new kernel releases break it, though.

**Comment by ajn142** [comment]
Evening,

Any chance of seeing a branch to port the driver to 4.15? The init_timer function has been deprecated in 4.15, and it results in this failing to compile. I've tried to make some adjustments to the code myself, but unfortunately my dev experience is effectively nil. I did find a driver for a different chipset that seems to have ported effectively to 4.15, but it seems that there are some minor differences in variable names, and I don't understand the code well enough to fix that.

https://github.com/ulli-kroll/mt7610u/issues/61

https://github.com/ulli-kroll/mt7610u/commit/484596c98b96ca67b98f8c04a005c45b20c759b7#diff-7c0adccc456e6ca9798eaadcfce80a1a

My apologies if this isn't the right place to ask, but I couldn't manage to find another.

**Comment by kaduke** [comment]
@ajn142 I've got a working port to 4.15 branch in my fork of this repository. 

https://github.com/kaduke/Netgear-A6210/tree/port-to-4.15

@genodeftest Would this be something you'd want pulled into your fork? If you can create a port-to-4.15 branch on your fork, I'll open a PR to merge my branch into it.

**Comment by genodeftest** [comment]
@kaduke I'm not using this driver actively. Would you be interested in creating a separate GitHub organization, invite some of the people here and on the original repo (you can add me if you want) and transfer or fork your repo there? I think a multi-maintainer repo would be the best solution here.

If you want, I can create the GitHub organization instead.

**Pull request merged**
